import { Link } from 'react-router-dom'

const CONTACT_EMAIL = 'shreeyadav375@gmail.com'
const LAST_UPDATED = '6 October 2026'

type Section = { heading: string; body: string[] }

const PRIVACY: Section[] = [
  {
    heading: 'What ChronoLegal is',
    body: [
      'ChronoLegal is a final-year academic project: an AI-assisted legal research platform for Indian case law. It is a demonstration system, not a commercial service, and it does not provide legal advice.',
    ],
  },
  {
    heading: 'Information we collect',
    body: [
      'Account details: your email address, username, optional full name, and a securely hashed password if you register with email and password.',
      'If you choose "Continue with Google": your Google account identifier, email address, name and profile picture, as shared by Google with your consent. We request only the basic openid, email and profile permissions — never access to your Gmail, Drive, contacts or any other Google data.',
      'Content you provide: judgments you upload, questions you ask, and the resulting conversations and feedback.',
    ],
  },
  {
    heading: 'How we use it',
    body: [
      'To sign you in, keep your session active, and show you your own conversations and uploaded judgments.',
      'To answer research questions: relevant excerpts of indexed judgments and your question are sent to the Groq API to generate an answer with citations.',
      'We do not sell, rent or share your personal information with advertisers, and we do not use it for marketing.',
    ],
  },
  {
    heading: 'Where it is stored',
    body: [
      'Account and case data are stored in a Supabase PostgreSQL database; search indexes are stored on the project server. Access tokens are stored in your browser so you stay signed in until you log out.',
    ],
  },
  {
    heading: 'Your choices',
    body: [
      'You can stop using ChronoLegal at any time. To have your account and associated data deleted, email us at the address below. You can also revoke ChronoLegal\'s access to your Google account at any time from your Google Account → Security → Third-party connections.',
    ],
  },
]

const TERMS: Section[] = [
  {
    heading: 'About the service',
    body: [
      'ChronoLegal is provided as an academic final-year project for demonstration and research purposes, free of charge, without any guarantee of availability.',
    ],
  },
  {
    heading: 'Not legal advice',
    body: [
      'Answers are generated by an AI system from indexed judgments and may be incomplete or incorrect. Nothing on ChronoLegal is legal advice; always verify against the original judgment and consult a qualified advocate before relying on it.',
    ],
  },
  {
    heading: 'Acceptable use',
    body: [
      'Upload only documents you are entitled to share. Do not attempt to disrupt the service, access other users\' accounts or data, or use the service for unlawful purposes.',
    ],
  },
  {
    heading: 'Accounts',
    body: [
      'You are responsible for activity under your account. Accounts may be suspended or removed if these terms are breached or when the project demonstration ends.',
    ],
  },
  {
    heading: 'Changes',
    body: ['These terms may be updated as the project evolves; the date below shows the latest revision.'],
  },
]

export default function LegalPage({ kind }: { kind: 'privacy' | 'terms' }) {
  const title = kind === 'privacy' ? 'Privacy Policy' : 'Terms of Service'
  const sections = kind === 'privacy' ? PRIVACY : TERMS

  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-10 sm:py-14">
        <Link to="/" className="inline-block mb-10">
          <img src="/chronolegal-logo.png" alt="ChronoLegal — Legal Research Platform" className="h-8 w-auto object-contain" />
        </Link>

        <h1 className="font-serif text-3xl sm:text-4xl font-bold text-foreground mb-2">{title}</h1>
        <p className="text-sm text-muted-foreground mb-10">Last updated: {LAST_UPDATED}</p>

        <div className="space-y-8">
          {sections.map((s) => (
            <section key={s.heading}>
              <h2 className="font-serif text-xl font-semibold text-foreground mb-3">{s.heading}</h2>
              <div className="space-y-3">
                {s.body.map((p) => (
                  <p key={p} className="text-[15px] leading-relaxed text-foreground/85">
                    {p}
                  </p>
                ))}
              </div>
            </section>
          ))}

          <section>
            <h2 className="font-serif text-xl font-semibold text-foreground mb-3">Contact</h2>
            <p className="text-[15px] leading-relaxed text-foreground/85">
              Questions or requests:{' '}
              <a href={`mailto:${CONTACT_EMAIL}`} className="text-primary hover:underline">
                {CONTACT_EMAIL}
              </a>
            </p>
          </section>
        </div>

        <div className="mt-14 pt-6 border-t border-border flex gap-6 text-sm text-muted-foreground">
          <Link to={kind === 'privacy' ? '/terms' : '/privacy'} className="hover:text-foreground transition-colors">
            {kind === 'privacy' ? 'Terms of Service' : 'Privacy Policy'}
          </Link>
          <Link to="/" className="hover:text-foreground transition-colors">
            Back to ChronoLegal
          </Link>
        </div>
      </div>
    </div>
  )
}
